const MaintenancePlan = require('../models/MaintenancePlan');
const WorkOrder = require('../models/WorkOrder');
const Alert = require('../models/Alert');
const Generator = require('../models/Generator');
const { notifyRoles } = require('./notificationService');
const { syncGeneratorStatus } = require('./workOrderService');
const realtime = require('./realtime');

const DAY_MS = 24 * 60 * 60 * 1000;
const NOTIFY_ROLES = ['Admin', 'Engineer', 'Technician'];

/**
 * Next-due point for a plan given its generator's current runtime.
 * Returns { mode, dueAt, dueRuntimeHours, due } where `due` accounts for lead time.
 */
const computeNextDue = (plan, generator) => {
  if (plan.intervalType === 'days') {
    const base = plan.lastGeneratedAt || plan.anchorDate || plan.createdAt || new Date();
    const dueAt = new Date(new Date(base).getTime() + plan.intervalValue * DAY_MS);
    const due = Date.now() >= dueAt.getTime() - (plan.leadTimeDays || 0) * DAY_MS;
    return { mode: 'days', dueAt, dueRuntimeHours: null, due };
  }
  const base = plan.lastGeneratedRuntimeHours ?? plan.anchorRuntimeHours ?? 0;
  const dueRuntimeHours = base + plan.intervalValue;
  const due = (generator?.runtimeHours ?? 0) >= dueRuntimeHours;
  return { mode: 'runtimeHours', dueAt: null, dueRuntimeHours, due };
};

/** Create work orders for every plan that is currently due. */
const generateDueWorkOrders = async () => {
  const plans = await MaintenancePlan.find({ isActive: true }).populate('generatorId');
  let created = 0;

  for (const plan of plans) {
    const generator = plan.generatorId;
    if (!generator || generator.isDecommissioned) continue;

    const { due, dueAt, dueRuntimeHours, mode } = computeNextDue(plan, generator);
    if (!due) continue;

    const alreadyOpen = await WorkOrder.exists({
      planId: plan._id,
      status: { $in: WorkOrder.ACTIVE_STATUSES },
    });
    if (alreadyOpen) continue;

    const workOrder = await WorkOrder.create({
      generatorId: generator._id,
      siteId: generator.siteId,
      planId: plan._id,
      title: plan.name,
      description:
        mode === 'days'
          ? `Auto-generated from plan "${plan.name}" (every ${plan.intervalValue} days).`
          : `Auto-generated from plan "${plan.name}" (every ${plan.intervalValue} runtime hours).`,
      type: 'preventive',
      priority: plan.priority === 'high' ? 'high' : plan.priority === 'low' ? 'low' : 'medium',
      status: 'open',
      scheduledDate: dueAt || new Date(),
      slaDueAt: new Date(Date.now() + (plan.slaDays || 7) * DAY_MS),
      checklist: (plan.checklist || []).map((label) => ({ label, done: false })),
      timeline: [{ at: new Date(), action: 'create', note: 'Generated by maintenance scheduler' }],
    });

    plan.lastGeneratedAt = new Date();
    plan.lastGeneratedRuntimeHours = generator.runtimeHours ?? 0;
    await plan.save();
    await syncGeneratorStatus(generator._id);

    realtime.emitAll('workorder:new', { id: workOrder._id, code: workOrder.code });
    await notifyRoles(NOTIFY_ROLES, {
      title: `PM work order created: ${plan.name}`,
      body: `${generator.generatorId} — ${workOrder.code}`,
      type: 'maintenance',
      link: '/work-orders',
      workOrderId: workOrder._id,
      severity: 'info',
    });
    created += 1;
  }

  return { created };
};

/** Open/refresh MaintenanceOverdue alerts for SLA-breached work orders; clear when none remain. */
const flagOverdueWorkOrders = async () => {
  const now = new Date();
  const overdue = await WorkOrder.find({
    status: { $in: WorkOrder.ACTIVE_STATUSES },
    slaDueAt: { $lt: now },
  }).populate('generatorId', 'generatorId siteId');

  const overdueGeneratorIds = new Set();
  let opened = 0;

  for (const wo of overdue) {
    const generatorId = wo.generatorId?._id || wo.generatorId;
    if (!generatorId) continue;
    overdueGeneratorIds.add(String(generatorId));

    const existing = await Alert.findOne({
      generatorId,
      type: 'MaintenanceOverdue',
      status: { $in: ['open', 'acknowledged'] },
    });

    if (existing) {
      existing.lastSeenAt = now;
      existing.message = `Maintenance overdue: ${wo.code} — ${wo.title}`;
      await existing.save();
    } else {
      const alert = await Alert.create({
        generatorId,
        siteId: wo.siteId,
        type: 'MaintenanceOverdue',
        severity: 'warning',
        message: `Maintenance overdue: ${wo.code} — ${wo.title}`,
        firstSeenAt: now,
        lastSeenAt: now,
      });
      realtime.emitAll('alert:new', alert.toJSON());
      await notifyRoles(NOTIFY_ROLES, {
        title: `Maintenance overdue: ${wo.title}`,
        body: `${wo.generatorId?.generatorId || ''} — ${wo.code}`,
        type: 'maintenance',
        link: '/work-orders',
        workOrderId: wo._id,
        severity: 'warning',
      });
      opened += 1;
    }
  }

  // Auto-resolve overdue alerts for generators no longer breached.
  const staleOverdue = await Alert.find({
    type: 'MaintenanceOverdue',
    status: { $in: ['open', 'acknowledged'] },
  });
  let resolved = 0;
  for (const alert of staleOverdue) {
    if (!overdueGeneratorIds.has(String(alert.generatorId))) {
      alert.status = 'resolved';
      alert.resolvedAt = now;
      alert.autoResolved = true;
      await alert.save();
      realtime.emitAll('alert:updated', alert.toJSON());
      resolved += 1;
    }
  }

  return { opened, resolved };
};

const sweep = async () => {
  const gen = await generateDueWorkOrders();
  const overdue = await flagOverdueWorkOrders();
  return { ...gen, ...overdue };
};

module.exports = { computeNextDue, generateDueWorkOrders, flagOverdueWorkOrders, sweep };
